import type { Event, EventCity, Organizer } from "./types"

export const categories = ["Jatra", "Cinema", "Music", "Dance", "Festivals", "Workshops", "Custom Orders"]

export const trendingCities: EventCity[] = [
  {
    name: "Bhubaneswar",
    country: "Odisha, India",
    eventCount: 245,
    image: "/bhubaneswar-odisha-cultural-city.jpg",
    coordinates: { lat: 20.2961, lng: 85.8245 },
  },
  {
    name: "Delhi",
    country: "India",
    eventCount: 892,
    image: "/delhi-india-cultural-hub.jpg",
    coordinates: { lat: 28.7041, lng: 77.1025 },
  },
  {
    name: "Mumbai",
    country: "India",
    eventCount: 756,
    image: "/mumbai-india-arts-scene.jpg",
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    name: "Kolkata",
    country: "India",
    eventCount: 634,
    image: "/kolkata-india-cultural-capital.jpg",
    coordinates: { lat: 22.5726, lng: 88.3639 },
  },
  {
    name: "Bangalore",
    country: "India",
    eventCount: 521,
    image: "/bangalore-india-tech-arts-fusion.jpg",
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },
  {
    name: "New York",
    country: "USA",
    eventCount: 412,
    image: "/new-york-global-arts-stage.jpg",
    coordinates: { lat: 40.7128, lng: -74.006 },
  },
]

const organizers: Organizer[] = [
  {
    id: "1",
    name: "Odisha Classical Arts",
    image: "/odisha-arts-collective-logo.jpg",
    verified: true,
    events: 42,
    followers: 5200,
  },
  {
    id: "2",
    name: "Global Jatra Collective",
    image: "/jatra-theatre-logo.jpg",
    verified: true,
    events: 28,
    followers: 8400,
  },
  {
    id: "3",
    name: "Dance India Movement",
    image: "/dance-arts-logo.jpg",
    verified: true,
    events: 15,
    followers: 2100,
  },
  {
    id: "4",
    name: "MOOKALAA Artists Network",
    image: "/mookalaa-platform-logo.jpg",
    verified: true,
    events: 54,
    followers: 12000,
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Odissi Dance Festival 2025",
    description:
      "Celebrate the grace and elegance of Odissi dance with performances from acclaimed dancers. Experience traditional choreography and contemporary interpretations.",
    image: "/odissi-dance-festival-performance-stage.jpg",
    date: new Date("2025-02-15"),
    time: "06:00 PM",
    endDate: new Date("2025-02-15"),
    location: "Rabindra Mandap, Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Dance",
    price: 299,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 2341,
    tags: ["Odissi", "Dance", "Classical", "Traditional Art"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "2",
    title: "Jatra Theatre Festival - Stories of Bengal",
    description:
      "Immerse yourself in the vibrant world of Jatra - traditional folk theatre. Experience compelling narratives performed by master artists.",
    image: "/jatra-traditional-theatre-performance.jpg",
    hoverVideo: "/video/Video_Generation_Complete.mp4",
    date: new Date("2025-02-22"),
    time: "07:00 PM",
    endDate: new Date("2025-02-24"),
    location: "Siddeshwari Auditorium, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Jatra",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 5234,
    tags: ["Jatra", "Theatre", "Folk Art", "Traditional"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "3",
    title: "Learn Kathak Dance Online",
    description:
      "Master the fundamentals of Kathak dance in this comprehensive online workshop. Learn from Kathak maestro with personalized feedback.",
    image: "/kathak-dance-online-workshop.jpg",
    date: new Date("2025-02-10"),
    time: "06:00 PM",
    endDate: new Date("2025-03-10"),
    location: "Online",
    city: "Virtual",
    coordinates: { lat: 0, lng: 0 },
    category: "Workshops",
    price: 0,
    isFree: true,
    isOnline: true,
    organizer: organizers[2],
    attendees: 1234,
    tags: ["Kathak", "Dance", "Online", "Workshop"],
    rating: 4.5,
  },
  {
    id: "4",
    title: "Indie Cinema Showcase 2025",
    description:
      "Discover independent films from emerging filmmakers across India and the world. Q&A sessions with directors.",
    image: "/film-festival-cinema-screening.jpg",
    date: new Date("2025-03-01"),
    time: "02:00 PM",
    endDate: new Date("2025-03-03"),
    location: "PVR Cinemas, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Cinema",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 892,
    tags: ["Cinema", "Indie Films", "Festival", "Documentary"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "5",
    title: "Custom Personalized Song from Bollywood Artists",
    description:
      "Commission a personalized song, birthday greeting, or special message from professional Bollywood singers. Perfect for celebrations!",
    image: "/bollywood-singer-recording-studio.jpg",
    date: new Date("2025-03-15"),
    time: "12:00 PM",
    location: "Online - Delivery",
    city: "Virtual",
    coordinates: { lat: 0, lng: 0 },
    category: "Custom Orders",
    price: 499,
    isFree: false,
    isOnline: true,
    organizer: organizers[0],
    attendees: 234,
    tags: ["Custom Order", "Music", "Bollywood", "Gift"],
    rating: 4.6,
  },
  {
    id: "6",
    title: "Holi Festival - Music & Dance Celebration",
    description:
      "Celebrate the festival of colors with live music performances, traditional dances, and cultural celebrations.",
    image: "/holi-festival-celebration.jpg",
    date: new Date("2025-03-10"),
    time: "04:00 PM",
    location: "Cultural Centre, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Festivals",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[3],
    attendees: 89,
    tags: ["Holi", "Festival", "Music", "Culture"],
    rating: 4.4,
  },
  {
    id: "7",
    title: "Indian Classical Music Masterclass",
    description:
      "Learn Indian classical music from Grammy-nominated musician. Cover raag theory, instrument techniques, and composition.",
    image: "/indian-classical-music-masterclass.jpg",
    date: new Date("2025-02-28"),
    time: "10:00 AM",
    location: "Ravindra Sarovar, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Workshops",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1567,
    tags: ["Classical Music", "Masterclass", "Learning", "Workshop"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "8",
    title: "Global Arts Summit - New York",
    description:
      "Connect with international artists, curators, and culture enthusiasts. Showcase your work to a global audience.",
    image: "/global-arts-summit-networking.jpg",
    date: new Date("2025-03-20"),
    time: "09:00 AM",
    endDate: new Date("2025-03-22"),
    location: "Lincoln Center, New York, USA",
    city: "New York",
    coordinates: { lat: 40.7128, lng: -74.006 },
    category: "Festivals",
    price: 799,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 3456,
    tags: ["Global", "Summit", "Arts", "Networking"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "9",
    title: "Bharatanatyam Dance Workshop for Beginners",
    description:
      "Learn the classical South Indian dance form Bharatanatyam from experienced instructors. Perfect for beginners with no prior experience.",
    image: "/bharatanatyam-dance-workshop.jpg",
    date: new Date("2025-02-20"),
    time: "05:00 PM",
    location: "Arts Academy, Chennai, Tamil Nadu",
    city: "Chennai",
    coordinates: { lat: 13.0827, lng: 80.2707 },
    category: "Workshops",
    price: 149,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 456,
    tags: ["Bharatanatyam", "Dance", "Beginners", "Classical"],
    rating: 4.6,
  },
  {
    id: "10",
    title: "Digital Art & Animation Expo",
    description:
      "Showcase digital artworks, animations, and interactive installations from emerging digital artists. Networking with tech & art professionals.",
    image: "/digital-art-animation-expo.jpg",
    date: new Date("2025-03-08"),
    time: "11:00 AM",
    endDate: new Date("2025-03-10"),
    location: "Tech Hub, Hyderabad, Telangana",
    city: "Hyderabad",
    coordinates: { lat: 17.385, lng: 78.4867 },
    category: "Festivals",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 1234,
    tags: ["Digital Art", "Animation", "Expo", "Technology"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "11",
    title: "Traditional Puppet Theater Show - Kathputli",
    description:
      "Experience the ancient art of Kathputli puppet theater with live performances depicting traditional Indian folklore and mythology.",
    image: "/kathputli-puppet-theater-show.jpg",
    date: new Date("2025-02-25"),
    time: "07:30 PM",
    location: "Heritage Theater, Jaipur, Rajasthan",
    city: "Jaipur",
    coordinates: { lat: 26.9124, lng: 75.7873 },
    category: "Festivals",
    price: 175,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 678,
    tags: ["Kathputli", "Puppet Theater", "Traditional", "Folklore"],
    rating: 4.5,
  },
  {
    id: "12",
    title: "Sitar Recital by Maestro",
    description:
      "An evening of classical Hindustani music featuring maestro sitar player performing raags from morning to night traditions.",
    image: "/sitar-recital-classical-music.jpg",
    hoverVideo: "/video/Make_a_video_202512011713.mp4",
    date: new Date("2025-03-05"),
    time: "06:00 PM",
    location: "Sapru House, New Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.6129, lng: 77.201 },
    category: "Music",
    price: 399,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 2100,
    tags: ["Sitar", "Classical", "Hindustani Music", "Maestro"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "13",
    title: "Street Art & Graffiti Workshop",
    description:
      "Learn urban art and graffiti techniques from professional street artists. Create your own mural with proper guidance and safety.",
    image: "/street-art-graffiti-workshop.jpg",
    date: new Date("2025-03-12"),
    time: "02:00 PM",
    location: "Art District, Pune, Maharashtra",
    city: "Pune",
    coordinates: { lat: 18.5204, lng: 73.8567 },
    category: "Workshops",
    price: 299,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 321,
    tags: ["Street Art", "Graffiti", "Workshop", "Urban Art"],
    rating: 4.4,
  },
  {
    id: "14",
    title: "Photography Exhibition - Faces of India",
    description:
      "A powerful photography exhibition showcasing portraits and stories of ordinary people from across India. Interactive artist talks.",
    image: "/photography-exhibition-faces-of-india.jpg",
    date: new Date("2025-03-16"),
    time: "10:00 AM",
    endDate: new Date("2025-03-25"),
    location: "Gallery Central, Ahmedabad, Gujarat",
    city: "Ahmedabad",
    coordinates: { lat: 23.0225, lng: 72.5714 },
    category: "Festivals",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1890,
    tags: ["Photography", "Exhibition", "Portrait", "Art"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "15",
    title: "Odissi Dance Festival - Classical Heritage",
    description:
      "Experience the divine grace of Odissi dance with master performers showcasing classical choreography and contemporary interpretations.",
    image: "/odissi-dance-festival-performance-stage.jpg",
    hoverVideo: "/video/1764583058940.mp4",
    date: new Date("2025-02-26"),
    time: "07:00 PM",
    endDate: new Date("2025-02-28"),
    location: "Kalinga Stadium, Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Jatra",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 3200,
    tags: ["Odissi", "Dance", "Classical", "Heritage"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "16",
    title: "Kathak Dance Performance with Live Music",
    description:
      "Experience the elegance of Kathak dance accompanied by live classical music. Master dancers perform traditional choreography with tabla and sitar accompaniment.",
    image: "/kathak-dance-online-workshop.jpg",
    hoverVideo: "/video/Video_Generation_Complete-222.mp4",
    date: new Date("2025-03-08"),
    time: "07:30 PM",
    location: "Music Academy, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Music",
    price: 275,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 850,
    tags: ["Kathak", "Dance", "Classical Music", "Live Performance"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "17",
    title: "Traditional Jatra Folk Theatre",
    description:
      "Experience authentic Bengali folk theatre with traditional Jatra performances featuring mythological stories and social themes.",
    image: "/bharatanatyam-dance-workshop.jpg",
    date: new Date("2025-03-12"),
    time: "08:00 PM",
    location: "Folk Theatre Hall, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Jatra",
    price: 180,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 1200,
    tags: ["Jatra", "Folk Theatre", "Bengali", "Traditional"],
    featured: true,
    rating: 4.6,
  },
  {
    id: "18",
    title: "Indian Classical Music Concert",
    description:
      "An enchanting evening of Indian classical music featuring renowned musicians performing traditional ragas and compositions.",
    image: "/indian-classical-music-masterclass.jpg",
    hoverVideo: "/video/Make_a_video_202512011722.mp4",
    date: new Date("2025-03-15"),
    time: "07:00 PM",
    location: "Music Auditorium, Chennai, Tamil Nadu",
    city: "Chennai",
    coordinates: { lat: 13.0827, lng: 80.2707 },
    category: "Music",
    price: 320,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1500,
    tags: ["Classical Music", "Concert", "Ragas", "Traditional"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "19",
    title: "Documentary Film Festival",
    description:
      "A curated selection of award-winning documentaries from around the world, featuring stories of culture, society, and human experiences.",
    image: "/digital-art-animation-expo.jpg",
    date: new Date("2025-03-18"),
    time: "06:00 PM",
    endDate: new Date("2025-03-20"),
    location: "Cinema Complex, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Cinema",
    price: 150,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 650,
    tags: ["Documentary", "Film Festival", "Cinema", "Culture"],
    featured: true,
    rating: 4.5,
  },
  {
    id: "20",
    title: "International Short Film Showcase",
    description:
      "A collection of award-winning short films from international filmmakers, showcasing diverse storytelling and innovative cinematography.",
    image: "/street-art-graffiti-workshop.jpg",
    date: new Date("2025-03-22"),
    time: "05:30 PM",
    location: "Art Cinema Hall, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Cinema",
    price: 120,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 480,
    tags: ["Short Films", "International", "Cinema", "Showcase"],
    featured: true,
    rating: 4.6,
  },
]
